title: Heitor Gouvêa
description: >
    I work with amazing companies on projects that help people, organizations, and companies take control of their own information.
keywords: Heitor Gouvêa, Security Researcher, Independent, Vulnerability Researcher, Pentester, Bug Bounty Hunter, Perl, Fuzzing, Nipe, Nozaki, Uranus, Spellbook
author: Heitor Gouvêa
baseurl: "" 
url: "https://heitorgouvea.me" 

twitter_username: htrgouvea
github_username:  htrgouvea
donate: donate

include: [_pages]
exclude: ["README.md", "SECURITY.md", "LICENSE.md", "Gemfile", "Dockerfile"]

markdown: kramdown
permalink: /:year/:month/:day/:title

sass:
    style: compressed
plugins:
  - jemoji
  - jekyll-sitemap

google_analytics: UA-105655736-1